#!/bin/bash
file="/home/raitaro/.conky/MyConky/GothamDarkKDE"
var=`cat $file | grep "EAEAEA"`
if [[ $var != "" ]]; then
    echo "Making dark"
    sed -i -- "s/default_color\ EAEAEA/default_color\ 31363b/g" $file
else
    echo "Making white"
    sed -i -- "s/default_color\ 31363b/default_color\ EAEAEA/g" $file
fi

